---
# %BEGIN_COPYRIGHT%
# 
# Copyright 2015-2018 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# Find any files in the directory specified using the -regex option
# of find(1).
- hosts: "{{ hosts | default('localhost') }}"
  name: "Find any files in the directory specified"
  become: yes

  vars_prompt:
    - name: "directory_name"
      prompt: "Enter the directory name to find files in"
      private: no

    - name: "regex_to_find"
      prompt: "Enter the file name to find (eg *.jpg, sys*.conf)"
      private: no

  vars:
        upload_dest_directory: "../../uploaded_files"
#       print_information: true

  tasks:
    - include: ../common/common_information.yml

    - name: Invalid directory name
      local_action: command printf "Invalid directory name."
      when: directory_name == ""
      failed_when: true

    - name: Invalid regex file name
      local_action: command printf "Invalid file name."
      when: regex_to_find == ""
      failed_when: true

    # The ansible find module ships >= 2.0.0. Convert this
    # to use the find module when Centos 6 ansible >= 2.0.0
    # find: paths="/etc/" patterns="^.*?\.(?:rpmnew|rpmsave)$" use_regex=true
    - name: Find files in the directory specified using regex
      script: scripts/find_files "{{ directory_name | quote }}" "{{ regex_to_find | quote }}"
      register: file_info
      changed_when: false
      failed_when: file_info.rc > 0

    - include: ../common/common_find_files.yml
