---
# %BEGIN_COPYRIGHT%
# 
# Copyright 2015-2018 Ian McWilliam (kaosagnt@gmail.com).
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# %END_COPYRIGHT%

# Open a network port in iptables / firewalld.
- hosts: "{{ hosts | default('localhost') }}"
  name: "Open a network port in iptables/firewalld"
  become: yes

  vars:
       source_ip_s: " "
       protocol_s: "tcp"
#       print_information: true

  vars_prompt:
    - name: "port_numbers"
      prompt: "Enter the port number(s)\n(seperated by a comma for multiple ports)"
      private: no

    - name: "protocol"
      prompt: "\nEnter the TCP/IP protocol for the port(s) (leave blank for default 'tcp')"
      private: no

    - name: "source_ip"
      prompt: "\nEnter the source IP / network to restrict port access (leave blank for all network access)"
      private: no

  tasks:
    - include: ../../common/common_information.yml

    - include: network-common-checks.yml

#                  insertafter="^:OUTPUT \[\d*:\d*\]$"
#                  regexp="--dport {{ item }} -j ACCEPT"

    - name: Insert iptables rule for port(s) provided 
      lineinfile:
                 dest: /etc/sysconfig/iptables
                 create: yes
                 state: present
                 regexp: "-A INPUT{{source_ip_s}}-m state --state NEW -m {{ protocol_s }} -p {{ protocol_s }} --dport {{ item }} -j ACCEPT"
                 insertbefore: "^-A INPUT -j REJECT"
                 line: "-A INPUT{{source_ip_s}}-m state --state NEW -m {{ protocol_s }} -p {{ protocol_s }} --dport {{ item }} -j ACCEPT"
      when: (ansible_os_family == 'RedHat')
            and
            (ansible_lsb.major_release|int <= 6)
      register: add_port_iptables
      notify: Restart iptables
      with_items:
        - "{{ port_numbers.split(',') }}"

    # NOTE: source='source_address' added in ansible >=2.0
    - name: Insert firewalld rule for port(s) provided
      firewalld:
                port: "{{ item }}/{{ protocol_s }}"
                permanent: true
                state: enabled
                immediate: yes
      when: ((ansible_os_family == 'RedHat')
            and
            (ansible_lsb.major_release|int >= 7))
      register: add_port_firewalld
      with_items:
        - "{{ port_numbers.split(',') }}"

  handlers:
    - include: ../common/common_handlers.yml
